source "https://rubygems.org"

gem "awesome_print"
gem "ruby-progressbar"
gem "erb"
gem "cgi", ">= 0.3.7"
gem "tilt"
gem "json"
gem "ostruct"
gem "optimist"
gem "fileutils"
gem "paint"
gem "terminal-table"
gem "bytesize"
gem "digest-crc"
gem "base64"
